-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation postFloatingIps_Id_ActionsChangeProtection
module HCloud.Operations.PostFloatingIpsIdActionsChangeProtection where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified HCloud.Common
import HCloud.Types

-- | > POST /floating_ips/{id}/actions/change_protection
-- 
-- Changes the protection configuration of the Floating IP.
postFloatingIps_Id_ActionsChangeProtection :: forall m . HCloud.Common.MonadHTTP m => GHC.Types.Int -- ^ id: ID of the Floating IP
  -> GHC.Maybe.Maybe PostFloatingIpsIdActionsChangeProtectionRequestBody -- ^ The request body to send
  -> HCloud.Common.HttpT m (Network.HTTP.Client.Types.Response PostFloatingIpsIdActionsChangeProtectionResponse) -- ^ Monadic computation which returns the result of the operation
postFloatingIps_Id_ActionsChangeProtection id
                                           body = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either PostFloatingIpsIdActionsChangeProtectionResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 201) (Network.HTTP.Client.Types.responseStatus response) -> PostFloatingIpsIdActionsChangeProtectionResponse201 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             PostFloatingIpsIdActionsChangeProtectionResponseBody201)
                                                                                                                                                                                                                     | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (HCloud.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/floating_ips/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ HCloud.Common.stringifyModel id)) GHC.Base.++ "/actions/change_protection"))) GHC.Base.mempty body HCloud.Common.RequestBodyEncodingJSON)
-- | Defines the object schema located at @paths.\/floating_ips\/{id}\/actions\/change_protection.POST.requestBody.content.application\/json.schema@ in the specification.
-- 
-- 
data PostFloatingIpsIdActionsChangeProtectionRequestBody = PostFloatingIpsIdActionsChangeProtectionRequestBody {
  -- | delete: If true, prevents the Floating IP from being deleted
  postFloatingIpsIdActionsChangeProtectionRequestBodyDelete :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostFloatingIpsIdActionsChangeProtectionRequestBody
    where toJSON obj = Data.Aeson.Types.Internal.object ("delete" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionRequestBodyDelete obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("delete" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionRequestBodyDelete obj)
instance Data.Aeson.Types.FromJSON.FromJSON PostFloatingIpsIdActionsChangeProtectionRequestBody
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostFloatingIpsIdActionsChangeProtectionRequestBody" (\obj -> GHC.Base.pure PostFloatingIpsIdActionsChangeProtectionRequestBody GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "delete"))
-- | Create a new 'PostFloatingIpsIdActionsChangeProtectionRequestBody' with all required fields.
mkPostFloatingIpsIdActionsChangeProtectionRequestBody :: PostFloatingIpsIdActionsChangeProtectionRequestBody
mkPostFloatingIpsIdActionsChangeProtectionRequestBody = PostFloatingIpsIdActionsChangeProtectionRequestBody{postFloatingIpsIdActionsChangeProtectionRequestBodyDelete = GHC.Maybe.Nothing}
-- | Represents a response of the operation 'postFloatingIps_Id_ActionsChangeProtection'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'PostFloatingIpsIdActionsChangeProtectionResponseError' is used.
data PostFloatingIpsIdActionsChangeProtectionResponse =
   PostFloatingIpsIdActionsChangeProtectionResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | PostFloatingIpsIdActionsChangeProtectionResponse201 PostFloatingIpsIdActionsChangeProtectionResponseBody201 -- ^ The \`action\` key contains the \`change_protection\` Action
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | Defines the object schema located at @paths.\/floating_ips\/{id}\/actions\/change_protection.POST.responses.201.content.application\/json.schema@ in the specification.
-- 
-- 
data PostFloatingIpsIdActionsChangeProtectionResponseBody201 = PostFloatingIpsIdActionsChangeProtectionResponseBody201 {
  -- | action
  postFloatingIpsIdActionsChangeProtectionResponseBody201Action :: PostFloatingIpsIdActionsChangeProtectionResponseBody201Action
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201
    where toJSON obj = Data.Aeson.Types.Internal.object ("action" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201Action obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs ("action" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201Action obj)
instance Data.Aeson.Types.FromJSON.FromJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostFloatingIpsIdActionsChangeProtectionResponseBody201" (\obj -> GHC.Base.pure PostFloatingIpsIdActionsChangeProtectionResponseBody201 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "action"))
-- | Create a new 'PostFloatingIpsIdActionsChangeProtectionResponseBody201' with all required fields.
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201 :: PostFloatingIpsIdActionsChangeProtectionResponseBody201Action -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201Action'
  -> PostFloatingIpsIdActionsChangeProtectionResponseBody201
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201 postFloatingIpsIdActionsChangeProtectionResponseBody201Action = PostFloatingIpsIdActionsChangeProtectionResponseBody201{postFloatingIpsIdActionsChangeProtectionResponseBody201Action = postFloatingIpsIdActionsChangeProtectionResponseBody201Action}
-- | Defines the object schema located at @paths.\/floating_ips\/{id}\/actions\/change_protection.POST.responses.201.content.application\/json.schema.properties.action@ in the specification.
-- 
-- 
data PostFloatingIpsIdActionsChangeProtectionResponseBody201Action = PostFloatingIpsIdActionsChangeProtectionResponseBody201Action {
  -- | command: Command executed in the Action
  postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand :: Data.Text.Internal.Text
  -- | error: Error message for the Action if error occurred, otherwise null
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError :: (GHC.Maybe.Maybe PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError)
  -- | finished: Point in time when the Action was finished (in ISO-8601 format). Only set if the Action is finished otherwise null.
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id: ID of the Resource
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId :: GHC.Types.Int
  -- | progress: Progress of Action in percent
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress :: GHC.Types.Double
  -- | resources: Resources the Action relates to
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources :: ([PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources])
  -- | started: Point in time when the Action was started (in ISO-8601 format)
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted :: Data.Text.Internal.Text
  -- | status: Status of the Action
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus :: PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201Action
    where toJSON obj = Data.Aeson.Types.Internal.object ("command" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand obj : "error" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError obj : "finished" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished obj : "id" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId obj : "progress" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress obj : "resources" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources obj : "started" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted obj : "status" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("command" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand obj) GHC.Base.<> (("error" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError obj) GHC.Base.<> (("finished" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId obj) GHC.Base.<> (("progress" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress obj) GHC.Base.<> (("resources" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources obj) GHC.Base.<> (("started" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted obj) GHC.Base.<> ("status" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus obj))))))))
instance Data.Aeson.Types.FromJSON.FromJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201Action
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostFloatingIpsIdActionsChangeProtectionResponseBody201Action" (\obj -> (((((((GHC.Base.pure PostFloatingIpsIdActionsChangeProtectionResponseBody201Action GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "command")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "error")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "finished")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "progress")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "resources")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "started")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "status"))
-- | Create a new 'PostFloatingIpsIdActionsChangeProtectionResponseBody201Action' with all required fields.
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201Action :: Data.Text.Internal.Text -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand'
  -> GHC.Maybe.Maybe PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError'
  -> GHC.Maybe.Maybe Data.Text.Internal.Text -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished'
  -> GHC.Types.Int -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId'
  -> GHC.Types.Double -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress'
  -> [PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources] -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources'
  -> Data.Text.Internal.Text -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted'
  -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus'
  -> PostFloatingIpsIdActionsChangeProtectionResponseBody201Action
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201Action postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus = PostFloatingIpsIdActionsChangeProtectionResponseBody201Action{postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionCommand,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionError,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionFinished,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionProgress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStarted,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus}
-- | Defines the object schema located at @paths.\/floating_ips\/{id}\/actions\/change_protection.POST.responses.201.content.application\/json.schema.properties.action.properties.error@ in the specification.
-- 
-- Error message for the Action if error occurred, otherwise null
data PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError = PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError {
  -- | code: Fixed machine readable code
  postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode :: Data.Text.Internal.Text
  -- | message: Humanized error message
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError
    where toJSON obj = Data.Aeson.Types.Internal.object ("code" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode obj : "message" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("code" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode obj) GHC.Base.<> ("message" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage obj))
instance Data.Aeson.Types.FromJSON.FromJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError" (\obj -> (GHC.Base.pure PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "code")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "message"))
-- | Create a new 'PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError' with all required fields.
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError :: Data.Text.Internal.Text -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode'
  -> Data.Text.Internal.Text -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage'
  -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage = PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionError{postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorCode,
                                                                                                                                                                                                                                                                                           postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionErrorMessage}
-- | Defines the object schema located at @paths.\/floating_ips\/{id}\/actions\/change_protection.POST.responses.201.content.application\/json.schema.properties.action.properties.resources.items@ in the specification.
-- 
-- 
data PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources = PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources {
  -- | id: ID of the Resource
  postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId :: GHC.Types.Int
  -- | type: Type of resource referenced
  , postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources
    where toJSON obj = Data.Aeson.Types.Internal.object ("id" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId obj : "type" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("id" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId obj) GHC.Base.<> ("type" Data.Aeson.Types.ToJSON..= postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType obj))
instance Data.Aeson.Types.FromJSON.FromJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources" (\obj -> (GHC.Base.pure PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))
-- | Create a new 'PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources' with all required fields.
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources :: GHC.Types.Int -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId'
  -> Data.Text.Internal.Text -- ^ 'postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType'
  -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources
mkPostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType = PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionResources{postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesId,
                                                                                                                                                                                                                                                                                                      postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType = postFloatingIpsIdActionsChangeProtectionResponseBody201ActionResourcesType}
-- | Defines the enum schema located at @paths.\/floating_ips\/{id}\/actions\/change_protection.POST.responses.201.content.application\/json.schema.properties.action.properties.status@ in the specification.
-- 
-- Status of the Action
data PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus =
   PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumSuccess -- ^ Represents the JSON value @"success"@
  | PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumRunning -- ^ Represents the JSON value @"running"@
  | PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumError -- ^ Represents the JSON value @"error"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus
    where toJSON (PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusOther val) = val
          toJSON (PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumSuccess) = "success"
          toJSON (PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumRunning) = "running"
          toJSON (PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumError) = "error"
instance Data.Aeson.Types.FromJSON.FromJSON PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatus
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "success" -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumSuccess
                                            | val GHC.Classes.== "running" -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumRunning
                                            | val GHC.Classes.== "error" -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusEnumError
                                            | GHC.Base.otherwise -> PostFloatingIpsIdActionsChangeProtectionResponseBody201ActionStatusOther val)
-- | > POST /floating_ips/{id}/actions/change_protection
-- 
-- The same as 'postFloatingIps_Id_ActionsChangeProtection' but accepts an explicit configuration.
postFloatingIps_Id_ActionsChangeProtectionWithConfiguration :: forall m . HCloud.Common.MonadHTTP m => HCloud.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ id: ID of the Floating IP
  -> GHC.Maybe.Maybe PostFloatingIpsIdActionsChangeProtectionRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response PostFloatingIpsIdActionsChangeProtectionResponse) -- ^ Monadic computation which returns the result of the operation
postFloatingIps_Id_ActionsChangeProtectionWithConfiguration config
                                                            id
                                                            body = GHC.Base.fmap (\response_2 -> GHC.Base.fmap (Data.Either.either PostFloatingIpsIdActionsChangeProtectionResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 201) (Network.HTTP.Client.Types.responseStatus response) -> PostFloatingIpsIdActionsChangeProtectionResponse201 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              PostFloatingIpsIdActionsChangeProtectionResponseBody201)
                                                                                                                                                                                                                                      | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_2) response_2) (HCloud.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/floating_ips/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ HCloud.Common.stringifyModel id)) GHC.Base.++ "/actions/change_protection"))) GHC.Base.mempty body HCloud.Common.RequestBodyEncodingJSON)
-- | > POST /floating_ips/{id}/actions/change_protection
-- 
-- The same as 'postFloatingIps_Id_ActionsChangeProtection' but returns the raw 'Data.ByteString.Char8.ByteString'.
postFloatingIps_Id_ActionsChangeProtectionRaw :: forall m . HCloud.Common.MonadHTTP m => GHC.Types.Int -- ^ id: ID of the Floating IP
  -> GHC.Maybe.Maybe PostFloatingIpsIdActionsChangeProtectionRequestBody -- ^ The request body to send
  -> HCloud.Common.HttpT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
postFloatingIps_Id_ActionsChangeProtectionRaw id
                                              body = GHC.Base.id (HCloud.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/floating_ips/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ HCloud.Common.stringifyModel id)) GHC.Base.++ "/actions/change_protection"))) GHC.Base.mempty body HCloud.Common.RequestBodyEncodingJSON)
-- | > POST /floating_ips/{id}/actions/change_protection
-- 
-- The same as 'postFloatingIps_Id_ActionsChangeProtection' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
postFloatingIps_Id_ActionsChangeProtectionWithConfigurationRaw :: forall m . HCloud.Common.MonadHTTP m => HCloud.Common.Configuration -- ^ The configuration to use in the request
  -> GHC.Types.Int -- ^ id: ID of the Floating IP
  -> GHC.Maybe.Maybe PostFloatingIpsIdActionsChangeProtectionRequestBody -- ^ The request body to send
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
postFloatingIps_Id_ActionsChangeProtectionWithConfigurationRaw config
                                                               id
                                                               body = GHC.Base.id (HCloud.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/floating_ips/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ HCloud.Common.stringifyModel id)) GHC.Base.++ "/actions/change_protection"))) GHC.Base.mempty body HCloud.Common.RequestBodyEncodingJSON)
