name:                hcloud-haskell
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/hcloud-haskell#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  hcloud-haskell:
    source-dirs:      src
    main:             Main.hs
